### ISSUE TITLE
[JS-Controller 3.x] token no recognized

### ISSUE THREAD

**Issue by DutchmanNL** [iobroker-community-adapters/ioBroker.telegram#148]
after update to 0.3.x pushover messages cannot be send : 

toeken is newly created at pushover webpage for testing purpose

```

2020-04-08 20:35:16.932 - info: pushover.0 (8668) starting. Version 1.2.3 in /opt/iobroker/node_modules/iobroker.pushover, node: v10.19.0, js-controller: 3.0.3
2020-04-08 20:35:26.947 - info: pushover.0 (8668) Send pushover notification: {"message":"This is test notification!","title":"xxxxx","priority":"0"}
2020-04-08 20:35:27.408 - error: pushover.0 (8668) uncaught exception: application token is invalid
2020-04-08 20:35:27.409 - error: pushover.0 (8668) Error: application token is invalid
at Pushover.errors (/opt/iobroker/node_modules/iobroker.pushover/node_modules/pushover-notifications/lib/pushover.js:146:13)
at IncomingMessage. (/opt/iobroker/node_modules/iobroker.pushover/node_modules/pushover-notifications/lib/pushover.js:250:12)
at IncomingMessage.emit (events.js:203:15)
at endReadableNT (_stream_readable.js:1145:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
2020-04-08 20:35:27.911 - info: pushover.0 (8668) terminating
2020-04-08 20:35:27.912 - info: pushover.0 (8668) Terminated (NO_ERROR): Without reason
```

**Comment by Apollon77** [comment]
wrong adapter :-) But ushiver 1.2.4 fixed on Github hopefully

**Comment by eric2905** [comment]
Still the same with js-controller 3.0.4
