### ISSUE TITLE
uncaught exception. socket hang up

### ISSUE THREAD

**Issue by Anzic23** [iobroker-community-adapters/ioBroker.telegram#152]
![image](https://user-images.githubusercontent.com/37106885/80450214-b1ed3a00-8929-11ea-80fb-4b197b50e08a.png)

the adapter is in server mode. 
"Store username instead of firstname of remembered users" is activate
telegram adapter v1.5.6
node: v12.16.2, 
js-controller: 3.0.19
the adapter restarts with this error:
```

2020-04-28 02:24:36.915 - error: telegram.0 (32264) uncaught exception: EFATAL: Error: socket hang up
--
2020-04-28 02:24:36.915 - error: telegram.0 (32264) RequestError: Error: socket hang up
at new RequestError (/opt/iobroker/node_modules/request-promise-core/lib/errors.js:14:15)
at Request.plumbing.callback (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:87:29)
at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:46:31)
at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
at Request.emit (events.js:310:20)
at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:881:8)
at ClientRequest.emit (events.js:310:20)
at TLSSocket.socketOnEnd (_http_client.js:460:9)
at TLSSocket.emit (events.js:322:22)
at endReadableNT (_stream_readable.js:1187:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-04-28 02:24:36.918 - debug: telegram.0 (32264) Send message to "Anzic23": Restarting...
2020-04-28 02:24:37.423 - info: telegram.0 (32264) terminating
2020-04-28 02:24:37.425 - info: telegram.0 (32264) Terminated (NO_ERROR): Without reason
2020-04-28 02:24:37.955 - info: host.iobroker instance system.adapter.telegram.0 terminated with code 0 (NO_ERROR)
2020-04-28 02:24:37.958 - info: host.iobroker Restart adapter system.adapter.telegram.0 because enabled
2020-04-28 02:24:38.995 - info: host.iobroker instance system.adapter.telegram.0 started with pid 10769
2020-04-28 02:24:40.968 - debug: telegram.0 (10769) Redis Objects: Use Redis connection: 0.0.0.0:9001
2020-04-28 02:24:40.996 - debug: telegram.0 (10769) Objects client ready ... initialize now
2020-04-28 02:24:41.002 - debug: telegram.0 (10769) Objects create System PubSub Client
2020-04-28 02:24:41.005 - debug: telegram.0 (10769) Objects create User PubSub Client
2020-04-28 02:24:41.006 - debug: telegram.0 (10769) Objects client initialize lua scripts
2020-04-28 02:24:41.024 - debug: telegram.0 (10769) Objects connected to redis: 0.0.0.0:9001
2020-04-28 02:24:41.028 - debug: telegram.0 (10769) objectDB connected
2020-04-28 02:24:41.030 - debug: telegram.0 (10769) Redis States: Use Redis connection: 0.0.0.0:6379
2020-04-28 02:24:41.034 - debug: telegram.0 (10769) States create User PubSub Client
2020-04-28 02:24:41.036 - debug: telegram.0 (10769) States create System PubSub Client
2020-04-28 02:24:41.041 - debug: telegram.0 (10769) States connected to redis: 0.0.0.0:6379
2020-04-28 02:24:41.042 - debug: telegram.0 (10769) statesDB connected
2020-04-28 02:24:42.263 - info: telegram.0 (10769) starting. Version 1.5.6 in /opt/iobroker/node_modules/iobroker.telegram, node: v12.16.2, js-controller: 3.0.19
2020-04-28 02:24:42.434 - debug: telegram.0 (10769) Schedule restart: 4 5 * * *
2020-04-28 02:24:43.017 - info: telegram.0 (10769) created middleware
2020-04-28 02:24:43.035 - info: telegram.0 (10769) LetsEncrypt challenge server is started on 8119
2020-04-28 02:24:43.036 - info: telegram.0 (10769) https server listening on port 88
2020-04-28 02:25:21.117 - debug: telegram.0 (10769) getMe: {"id":111111111,"is_bot":true,"first_name":"Умный дом","username":"smart_bot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false}
2020-04-28 02:25:21.121 - debug: telegram.0 (10769) Send message to "Anzic22223333": Started!
2020-04-28 02:25:21.327 - debug: telegram.0 (10769) Request: {"message_id":11111,"from":{"id":111111111,"is_bot":true,"first_name":"Умный дом","username":"smart_bot"},"chat":{"id":111111111,"first_name":"Anz","username":"Anzic22223333","type":"private"},"date":1588029921,"text":"Started!"}
2020-04-28 02:25:21.328 - debug: telegram.0 (10769) Message sent


```

**Comment by Apollon77** [comment]
"EFATAL: Error: socket hang up" means that while sending the request to pushover the connection got cancelled. Could it be that you had internet problems ... or they ?!

**Comment by Anzic23** [comment]
it's probably the Internet. Will be able to tell 01.05.2020.

**Comment by Anzic23** [comment]
internet problems
