### ISSUE TITLE
Beim Reconnect mit dem I-Net startet der Adapter durch

### ISSUE THREAD

**Issue by guergen1** [iobroker-community-adapters/ioBroker.telegram#158]
Seit ein paar Tagen startet der Adapter beim Reconnect nach der Zwangstrennung mit folgenden Fehlern durch:
Das Reconnecten hat ihm sonst nichts gemacht...
`

host.iobroker | 2020-05-09 08:31:09.803 | info | Restart adapter system.adapter.telegram.0 because enabled
-- | -- | -- | --
host.iobroker | 2020-05-09 08:31:09.801 | info | instance system.adapter.telegram.0 terminated with code 0 (NO_ERROR)
telegram.0 | 2020-05-09 08:31:09.282 | info | (24568) Terminated (NO_ERROR): Without reason
telegram.0 | 2020-05-09 08:31:09.282 | info | (24568) terminating
telegram.0 | 2020-05-09 08:31:08.775 | error | at processTicksAndRejections (internal/process/task_queues.js:84:21)
telegram.0 | 2020-05-09 08:31:08.775 | error | at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
telegram.0 | 2020-05-09 08:31:08.775 | error | at emitErrorNT (internal/streams/destroy.js:92:8)
telegram.0 | 2020-05-09 08:31:08.775 | error | at TLSSocket.emit (events.js:310:20)
telegram.0 | 2020-05-09 08:31:08.775 | error | at TLSSocket.socketErrorListener (_http_client.js:426:9)
telegram.0 | 2020-05-09 08:31:08.775 | error | at ClientRequest.emit (events.js:310:20)
telegram.0 | 2020-05-09 08:31:08.775 | error | at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:881:8)
telegram.0 | 2020-05-09 08:31:08.775 | error | at Request.emit (events.js:310:20)
telegram.0 | 2020-05-09 08:31:08.775 | error | at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
telegram.0 | 2020-05-09 08:31:08.775 | error | at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:46:31)
telegram.0 | 2020-05-09 08:31:08.775 | error | at Request.plumbing.callback (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:87:29)
telegram.0 | 2020-05-09 08:31:08.775 | error | at new RequestError (/opt/iobroker/node_modules/request-promise-core/lib/errors.js:14:15)
telegram.0 | 2020-05-09 08:31:08.775 | error | (24568) RequestError: Error: read ECONNRESET
telegram.0 | 2020-05-09 08:31:08.774 | error | (24568) uncaught exception: EFATAL: Error: read ECONNRESET
telegram.0 | 2020-05-09 08:31:08.736 | warn | (24568) polling_error:EFATAL, EFATAL: Error: read ECONNRESET

`

**Comment by Apollon77** [comment]
caused by https://github.com/yagop/node-telegram-bot-api/issues/798 most likely

**Comment by Diginix** [comment]
Bei mit ist der Adapter heute im Stop/Restart Loop mit diesem Fehler gelandet:
`2020-06-06 22:28:19.530  - [32minfo[39m: telegram.0 (35751) starting. Version 1.5.9 in /opt/iobroker/node_modules/iobroker.telegram, node: v12.18.0, js-controller: 3.1.5
2020-06-06 22:30:30.999  - [33mwarn[39m: telegram.0 (35751) polling_error:EFATAL, EFATAL: Error: connect ETIMEDOUT 149.154.167.220:443
2020-06-06 22:30:31.009  - [31merror[39m: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2020-06-06 22:30:31.010  - [31merror[39m: telegram.0 (35751) unhandled promise rejection: EFATAL: Error: connect ETIMEDOUT 149.154.167.220:443
2020-06-06 22:30:31.011  - [31merror[39m: telegram.0 (35751) RequestError: Error: connect ETIMEDOUT 149.154.167.220:443
    at new RequestError (/opt/iobroker/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-06-06 22:30:31.013  - [31merror[39m: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2020-06-06 22:30:31.014  - [31merror[39m: telegram.0 (35751) unhandled promise rejection: EFATAL: Error: connect ETIMEDOUT 149.154.167.220:443
2020-06-06 22:30:31.015  - [31merror[39m: telegram.0 (35751) RequestError: Error: connect ETIMEDOUT 149.154.167.220:443
    at new RequestError (/opt/iobroker/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-06-06 22:30:31.523  - [32minfo[39m: telegram.0 (35751) terminating
2020-06-06 22:30:31.525  - [32minfo[39m: telegram.0 (35751) Terminated (NO_ERROR): Without reason
`

nodejs 12.18.0
JS-Controller 3.1.5
