### ISSUE TITLE
Error: function without a catch block, or by rejecting a promise which  was not handled

### ISSUE THREAD

**Issue by Zefau** [iobroker-community-adapters/ioBroker.telegram#163]
```

telegram.0 | 2020-05-29 01:20:47.171 | error | at process._tickCallback (internal/process/next_tick.js:63:19)
-- | -- | -- | --
telegram.0 | 2020-05-29 01:20:47.171 | error | at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
telegram.0 | 2020-05-29 01:20:47.171 | error | at emitErrorNT (internal/streams/destroy.js:91:8)
telegram.0 | 2020-05-29 01:20:47.171 | error | at TLSSocket.emit (events.js:198:13)
telegram.0 | 2020-05-29 01:20:47.171 | error | at TLSSocket.socketErrorListener (_http_client.js:401:9)
telegram.0 | 2020-05-29 01:20:47.171 | error | at ClientRequest.emit (events.js:198:13)
telegram.0 | 2020-05-29 01:20:47.171 | error | at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:877:8)
telegram.0 | 2020-05-29 01:20:47.171 | error | at Request.emit (events.js:198:13)
telegram.0 | 2020-05-29 01:20:47.171 | error | at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
telegram.0 | 2020-05-29 01:20:47.171 | error | at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:46:31)
telegram.0 | 2020-05-29 01:20:47.171 | error | at Request.plumbing.callback (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:87:29)
telegram.0 | 2020-05-29 01:20:47.171 | error | at new RequestError (/opt/iobroker/node_modules/request-promise-core/lib/errors.js:14:15)
telegram.0 | 2020-05-29 01:20:47.171 | error | (22547) RequestError: Error: read ECONNRESET
telegram.0 | 2020-05-29 01:20:47.169 | error | (22547) unhandled promise rejection: EFATAL: Error: read ECONNRESET
Unhandled | 2020-05-29 01:20:47.166 | error | promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
telegram.0 | 2020-05-29 01:20:47.074 | warn | (22547) polling_error:EFATAL, EFATAL: Error: read ECONNRESET
```

**Comment by Apollon77** [comment]
duplicate #158
