### ISSUE TITLE
Telegram adapter does not turn green in Iobroker

### ISSUE THREAD

**Issue by Henny4184** [iobroker-community-adapters/ioBroker.telegram#164]
I had the Iobroker for about 2 weeks and then finally started again we also had some updates to adapters including telegram and since I have done the update and start the adapter I have the log always full and the adapter does not turn green. What could be the problem. See excerpt.

```
host.raspberrypi | 2020-05-29 14:05:45.224 | info | Update repository "default" under "http://download.iobroker.net/sources-dist.json"
-- | -- | -- | --
host.raspberrypi | 2020-05-29 14:05:17.874 | info | Do not restart adapter system.adapter.telegram.0 because disabled or deleted
host.raspberrypi | 2020-05-29 14:05:17.874 | error | instance system.adapter.telegram.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.raspberrypi | 2020-05-29 14:05:17.873 | error | Caught by controller[0]: }
host.raspberrypi | 2020-05-29 14:05:17.873 | error | Caught by controller[0]:   ]
host.raspberrypi | 2020-05-29 14:05:17.873 | error | Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.telegram/main.js'
host.raspberrypi | 2020-05-29 14:05:17.873 | error | Caught by controller[0]:     '/opt/iobroker/node_modules/node-telegram-bot-api/index.js',
host.raspberrypi | 2020-05-29 14:05:17.873 | error | Caught by controller[0]:     '/opt/iobroker/node_modules/node-telegram-bot-api/src/telegram.js',
host.raspberrypi | 2020-05-29 14:05:17.873 | error | Caught by controller[0]:     '/opt/iobroker/node_modules/array.prototype.findindex/index.js',
host.raspberrypi | 2020-05-29 14:05:17.873 | error | Caught by controller[0]:     '/opt/iobroker/node_modules/es-abstract/2019/RequireObjectCoercible.js',
host.raspberrypi | 2020-05-29 14:05:17.872 | error | Caught by controller[0]:     '/opt/iobroker/node_modules/es-abstract/5/CheckObjectCoercible.js',
host.raspberrypi | 2020-05-29 14:05:17.872 | error | Caught by controller[0]:   requireStack: [
host.raspberrypi | 2020-05-29 14:05:17.872 | error | Caught by controller[0]:   code: 'MODULE_NOT_FOUND',
host.raspberrypi | 2020-05-29 14:05:17.872 | error | Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:1026:19) {
host.raspberrypi | 2020-05-29 14:05:17.872 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
host.raspberrypi | 2020-05-29 14:05:17.872 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:986:32)
host.raspberrypi | 2020-05-29 14:05:17.872 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
host.raspberrypi | 2020-05-29 14:05:17.871 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
host.raspberrypi | 2020-05-29 14:05:17.871 | error | Caught by controller[0]:     at Object.<anonymous>  (/opt/iobroker/node_modules/es-abstract/5/CheckObjectCoercible.js:3:20)
host.raspberrypi | 2020-05-29 14:05:17.871 | error | Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:72:18)
host.raspberrypi | 2020-05-29 14:05:17.871 | error | Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:1026:19)
host.raspberrypi | 2020-05-29 14:05:17.871 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
host.raspberrypi | 2020-05-29 14:05:17.871 | error | Caught by controller[0]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
host.raspberrypi | 2020-05-29 14:05:17.871 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.telegram/main.js
host.raspberrypi | 2020-05-29 14:05:17.870 | error | Caught by controller[0]: - /opt/iobroker/node_modules/node-telegram-bot-api/index.js
host.raspberrypi | 2020-05-29 14:05:17.870 | error | Caught by controller[0]: - /opt/iobroker/node_modules/node-telegram-bot-api/src/telegram.js
host.raspberrypi | 2020-05-29 14:05:17.870 | error | Caught by controller[0]: - /opt/iobroker/node_modules/array.prototype.findindex/index.js
host.raspberrypi | 2020-05-29 14:05:17.870 | error | Caught by controller[0]: - /opt/iobroker/node_modules/es-abstract/2019/RequireObjectCoercible.js
host.raspberrypi | 2020-05-29 14:05:17.870 | error | Caught by controller[0]: - /opt/iobroker/node_modules/es-abstract/5/CheckObjectCoercible.js
host.raspberrypi | 2020-05-29 14:05:17.870 | error | Caught by controller[0]: Require stack:
host.raspberrypi | 2020-05-29 14:05:17.870 | error | Caught by controller[0]: Error: Cannot find module '../GetIntrinsic'
host.raspberrypi | 2020-05-29 14:05:17.870 | error | Caught by controller[0]:   ^
host.raspberrypi | 2020-05-29 14:05:17.869 | error | Caught by controller[0]:   throw err;
host.raspberrypi | 2020-05-29 14:05:17.869 | error | Caught by controller[0]: internal/modules/cjs/loader.js:969
host.raspberrypi | 2020-05-29 14:05:17.165 | info | "system.adapter.telegram.0" disabled
host.raspberrypi | 2020-05-29 14:05:16.528 | info | Restart adapter system.adapter.telegram.0 because enabled
host.raspberrypi | 2020-05-29 14:05:16.527 | error | instance system.adapter.telegram.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.raspberrypi | 2020-05-29 14:05:16.527 | error | Caught by controller[0]: }
host.raspberrypi | 2020-05-29 14:05:16.527 | error | Caught by controller[0]:   ]
host.raspberrypi | 2020-05-29 14:05:16.527 | error | Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.telegram/main.js'
host.raspberrypi | 2020-05-29 14:05:16.527 | error | Caught by controller[0]:     '/opt/iobroker/node_modules/node-telegram-bot-api/index.js',
host.raspberrypi | 2020-05-29 14:05:16.527 | error | Caught by controller[0]:     '/opt/iobroker/node_modules/node-telegram-bot-api/src/telegram.js',
host.raspberrypi | 2020-05-29 14:05:16.527 | error | Caught by controller[0]:     '/opt/iobroker/node_modules/array.prototype.findindex/index.js',
host.raspberrypi | 2020-05-29 14:05:16.526 | error | Caught by controller[0]:     '/opt/iobroker/node_modules/es-abstract/2019/RequireObjectCoercible.js',
host.raspberrypi | 2020-05-29 14:05:16.526 | error | Caught by controller[0]:     '/opt/iobroker/node_modules/es-abstract/5/CheckObjectCoercible.js',
host.raspberrypi | 2020-05-29 14:05:16.526 | error | Caught by controller[0]:   requireStack: [
host.raspberrypi | 2020-05-29 14:05:16.526 | error | Caught by controller[0]:   code: 'MODULE_NOT_FOUND',
host.raspberrypi | 2020-05-29 14:05:16.526 | error | Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:1026:19) {
host.raspberrypi | 2020-05-29 14:05:16.526 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
host.raspberrypi | 2020-05-29 14:05:16.526 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:986:32)
host.raspberrypi | 2020-05-29 14:05:16.525 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
host.raspberrypi | 2020-05-29 14:05:16.525 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
host.raspberrypi | 2020-05-29 14:05:16.525 | error | Caught by controller[0]:     at Object.<anonymous>  (/opt/iobroker/node_modules/es-abstract/5/CheckObjectCoercible.js:3:20)
host.raspberrypi | 2020-05-29 14:05:16.525 | error | Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:72:18)
host.raspberrypi | 2020-05-29 14:05:16.525 | error | Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:1026:19)
host.raspberrypi | 2020-05-29 14:05:16.525 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
host.raspberrypi | 2020-05-29 14:05:16.525 | error | Caught by controller[0]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
host.raspberrypi | 2020-05-29 14:05:16.525 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.telegram/main.js
host.raspberrypi | 2020-05-29 14:05:16.524 | error | Caught by controller[0]: - /opt/iobroker/node_modules/node-telegram-bot-api/index.js
host.raspberrypi | 2020-05-29 14:05:16.524 | error | Caught by controller[0]: - /opt/iobroker/node_modules/node-telegram-bot-api/src/telegram.js
host.raspberrypi | 2020-05-29 14:05:16.524 | error | Caught by controller[0]: - /opt/iobroker/node_modules/array.prototype.findindex/index.js
host.raspberrypi | 2020-05-29 14:05:16.524 | error | Caught by controller[0]: - /opt/iobroker/node_modules/es-abstract/2019/RequireObjectCoercible.js
host.raspberrypi | 2020-05-29 14:05:16.524 | error | Caught by controller[0]: - /opt/iobroker/node_modules/es-abstract/5/CheckObjectCoercible.js
host.raspberrypi | 2020-05-29 14:05:16.524 | error | Caught by controller[0]: Require stack:
host.raspberrypi | 2020-05-29 14:05:16.524 | error | Caught by controller[0]: Error: Cannot find module '../GetIntrinsic'
host.raspberrypi | 2020-05-29 14:05:16.523 | error | Caught by controller[0]:   ^
host.raspberrypi | 2020-05-29 14:05:16.523 | error | Caught by controller[0]:   throw err;
host.raspberrypi | 2020-05-29 14:05:16.523 | error | Caught by controller[0]: internal/modules/cjs/loader.js:969
host.raspberrypi | 2020-05-29 14:05:16.248 | info | instance system.adapter.telegram.0 started with pid 29500
host.raspberrypi | 2020-05-29 14:05:15.212 | info | Restart adapter system.adapter.telegram.0 because enabled
```

**Comment by Apollon77** [comment]
Please reinstall the adapter, it seems that a file is missing somehow

**Comment by Henny4184** [comment]
Hello, yes I think.  Reinstalling brings nothing already tried.  Now set the new to see what happens.  Tomorrow it continues.  I'm curious.

**Comment by Henny4184** [comment]
So, as already heard, the problem is that the update is well developed and I call the broker set up again. Now everything is running again. Thanks again.
