### ISSUE TITLE
massive Meldungen bei Internet-Zwangstrennung

### ISSUE THREAD

**Issue by fs-plugins** [iobroker-community-adapters/ioBroker.telegram#207]
Version 1.7.0
auf iobroker

ist so etwas unumgänglich? bin sicher nicht der einzige, welcher zwangsgetrennt wird
wäre toll wenn sich das vermeiden ließe

```
2021-02-15 01:55:35.452  - error:  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
--
2021-02-15 01:55:35.471  - error: telegram.0 (913) unhandled promise rejection: EFATAL: Error: read ECONNRESET
2021-02-15 01:55:35.472  - error: telegram.0 (913) RequestError: Error: read ECONNRESET
at new RequestError (/opt/iobroker/node_modules/request-promise-core/lib/errors.js:14:15)
at Request.plumbing.callback (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:87:29)
at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:46:31)
at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
at Request.emit (events.js:314:20)
at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:877:8)
at ClientRequest.emit (events.js:314:20)
at TLSSocket.socketErrorListener (_http_client.js:427:9)
at TLSSocket.emit (events.js:314:20)
at emitErrorNT (internal/streams/destroy.js:92:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-02-15 01:55:35.474  - error:  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
2021-02-15 01:55:35.475  - error: telegram.0 (913) unhandled promise rejection: EFATAL: Error: read ECONNRESET
2021-02-15 01:55:35.475  - error: telegram.0 (913) RequestError: Error: read ECONNRESET
at new RequestError (/opt/iobroker/node_modules/request-promise-core/lib/errors.js:14:15)
at Request.plumbing.callback (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:87:29)
at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:46:31)
at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
at Request.emit (events.js:314:20)
at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:877:8)
at ClientRequest.emit (events.js:314:20)
at TLSSocket.socketErrorListener (_http_client.js:427:9)
at TLSSocket.emit (events.js:314:20)
at emitErrorNT (internal/streams/destroy.js:92:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-02-15 01:55:35.485  - error:  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
2021-02-15 01:55:35.486  - error: telegram.0 (913) unhandled promise rejection: EFATAL: Error: read ECONNRESET
2021-02-15 01:55:35.486  - error: telegram.0 (913) RequestError: Error: read ECONNRESET
at new RequestError (/opt/iobroker/node_modules/request-promise-core/lib/errors.js:14:15)
at Request.plumbing.callback (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:87:29)
at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:46:31)
at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
at Request.emit (events.js:314:20)
at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:877:8)
at ClientRequest.emit (events.js:314:20)
at TLSSocket.socketErrorListener (_http_client.js:427:9)
at TLSSocket.emit (events.js:314:20)
at emitErrorNT (internal/streams/destroy.js:92:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-02-15 01:55:35.487  - error:  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
2021-02-15 01:55:35.487  - error: telegram.0 (913) unhandled promise rejection: EFATAL: Error: read ECONNRESET
2021-02-15 01:55:35.487  - error: telegram.0 (913) RequestError: Error: read ECONNRESET
at new RequestError (/opt/iobroker/node_modules/request-promise-core/lib/errors.js:14:15)
at Request.plumbing.callback (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:87:29)
at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:46:31)
at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
at Request.emit (events.js:314:20)
at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:877:8)
at ClientRequest.emit (events.js:314:20)
at TLSSocket.socketErrorListener (_http_client.js:427:9)
at TLSSocket.emit (events.js:314:20)
at emitErrorNT (internal/streams/destroy.js:92:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-02-15 01:55:35.488  - error:  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
2021-02-15 01:55:35.489  - error: telegram.0 (913) unhandled promise rejection: EFATAL: Error: read ECONNRESET
2021-02-15 01:55:35.490  - error: telegram.0 (913) RequestError: Error: read ECONNRESET
at new RequestError (/opt/iobroker/node_modules/request-promise-core/lib/errors.js:14:15)
at Request.plumbing.callback (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:87:29)
at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:46:31)
at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
at Request.emit (events.js:314:20)
at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:877:8)
at ClientRequest.emit (events.js:314:20)
at TLSSocket.socketErrorListener (_http_client.js:427:9)
at TLSSocket.emit (events.js:314:20)
at emitErrorNT (internal/streams/destroy.js:92:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-02-15 01:55:36.531  - info: host.iobroker instance system.adapter.telegram.0 terminated with code 0 (NO_ERROR)
2021-02-15 01:55:36.537  - info: host.iobroker Restart adapter system.adapter.telegram.0 because enabled
```

**Comment by Nahasapeemapetilon** [comment]
das Problem hatte ich auch schon festgestellt,
scheinen mehrere Stellen im Code zu gebenn bei dem der promise keinen catch-block hat,
die anderen Stellen sorgen bei mir allerdings nicht zu Problemen. Bei der Stelle wo ich den fix  hinzugefügt habe löst jedenfalls das Problem, dass der Adapter abschmiert abschmiert wenn der Router neu startet außerdem hat der (setinterval) keinen Intervall gehabt, das sorgte bei mir außerdem dafür das mein iobroker minutenlang nicht erreichbar war. hab erstmal 300ms gesetzt kann sein dass man da auch größeren Wert wählen kann bzw. direkt aus der adapter.conf ->pollinginterval  abgreift.

**Comment by fs-plugins** [comment]
ich vermute, da es nicht jede Nacht bei der Zwangstrennung auftritt, dass eine Intervalländerung keine wirkliche Anhilfe schafft weil ein Ablauf im script zufällig auf die getrennte Verbindung trifft
letztendlich wird da nur der Ersteller wirksam etwas ändern können

**Comment by Nahasapeemapetilon** [comment]
ich hab auch nen catch eingebaut ;)
bei mir stürzt der Adapter jedenfalls nicht mehr und er feuert nicht mehr in jede ms eine Anfrage ob die connection wieder da ist

**Comment by Apollon77** [comment]
@Nahasapeemapetilon den gleichen catch wie oben genannt? Wenn ja dann kann ich den PR mergen ... wenn nein, wo??

**Comment by Nahasapeemapetilon** [comment]
ja, sorry ich bezog mich auf den selben wie im fix.

**Comment by Apollon77** [comment]
I've added some more catches ... could you please check outgithub version if still everything works? (version number is the same)

**Comment by Nahasapeemapetilon** [comment]
so i have done three tests now
once router restart,once block with the firewall and cable out
each time the adapter no longer crashes
but it still floods massively into the log maybe you should think about displaying the message only at the first connection problem and then only again when it aborts again 
![error1](https://user-images.githubusercontent.com/16188935/108359802-bb190180-71f0-11eb-8a9f-31654bf560f7.JPG)
![error2](https://user-images.githubusercontent.com/16188935/108359804-bbb19800-71f0-11eb-8e76-56f5ed656bb9.JPG)

and I'm not sure if you really have to try to reconnect so fast maybe every second or every 5 seconds is enough
at a reboot of the router of ~3mins that's easily >600 error messages

**Comment by Apollon77** [comment]
Great feedback, up for another try?
Github updated
* connection checks every 1s instead 300ms
* only log every 10th
* log a success handling
* do not pile requests up on timeouts

**Comment by Nahasapeemapetilon** [comment]
the "getME" error handling works much better now, good idea to refactor it to settimeout and the counter

i think the 'polling_error' in line 1662 needs a similar counter
because it still reports strongly
with my test it came to different messages :
cable out:

(12052) polling_error:EFATAL, EFATAL: Error: getaddrinfo ENOTFOUND api.telegram.org
the message came approximately in the polling interval

if the firewall blocks the following message comes:

(12052) polling_error:EFATAL, EFATAL: Error: connect EACCES 149.154.167.220:443

and when the router reboots:
(12052) polling_error:EFATAL, EFATAL: Error: connect EACCES 149.154.167.220:443


![error_t01](https://user-images.githubusercontent.com/16188935/108428639-28ec1a00-723f-11eb-9da9-0d3e6f3a5e15.JPG)
![error_t02](https://user-images.githubusercontent.com/16188935/108428643-2984b080-723f-11eb-91e9-b171b7e5e2f0.JPG)
![error_t03](https://user-images.githubusercontent.com/16188935/108428645-2ab5dd80-723f-11eb-98e6-fb92b9d0d344.JPG)

**Comment by Apollon77** [comment]
Yes, right, other place, but here the polling is done by the lib. I truíed to do it differently here ... plese check GitHub again

**Comment by Nahasapeemapetilon** [comment]
so when router reboot I get only 5 message is fine for me thank you very much!

at firewall block and cable cut 
also only a few messages as long as the connection is interrupted 👌
have a nice weekend
![RouterError](https://user-images.githubusercontent.com/16188935/108514452-30093b80-72c4-11eb-88d0-3b398fe21c6a.JPG)
![CableError](https://user-images.githubusercontent.com/16188935/108514472-34cdef80-72c4-11eb-83df-2025e72adfc6.JPG)
![FirewallError](https://user-images.githubusercontent.com/16188935/108514477-35ff1c80-72c4-11eb-97ed-b88ceb6dc5b1.JPG)

**Comment by Apollon77** [comment]
Ok, cool and thank you for the intensive testing!! That helped a lot!
I will release that version then later today

**Comment by fs-plugins** [comment]
super! works perfectly with only one line 
many thanks
