### ISSUE TITLE
Error with media upload

### ISSUE THREAD

**Issue by HFarryranz** [iobroker-community-adapters/ioBroker.telegram#256]
save media files is checked.

when uploading jpg-file to bot i get this errorlog entry

uncaught exception: The "listener" argument must be of type Function. Received type boolean

telegram.0.communicate.pathFile   isn't updated.
 
There are no files in "/opt/iobroker/iobroker-data/tmp/telegram_0/photo"  saved.
Can't find the real name of the uploaded media file.

**Comment by Apollon77** [comment]
SOrry but I can not do anything with that information. Please provide a full original log - ideally debug log

**Comment by HFarryranz** [comment]
Node.js  v12.13.0 (Es gibt eine neuere Version: v12.22.5)
NPM     6.13.0
Telegram 1.10.0
 

`2021-08-19 12:02:48.599 - error: telegram.0 (2956) uncaught exception: The "listener" argument must be of type Function. Received type boolean
2021-08-19 12:02:48.610 - error: telegram.0 (2956) TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type boolean
at checkListener (events.js:64:11)
at _addListener (events.js:226:3)
at IncomingMessage.addListener (events.js:284:10)
at IncomingMessage.Readable.on (_stream_readable.js:867:35)
at ClientRequest. (/opt/iobroker/node_modules/iobroker.telegram/main.js:1042:21)
at Object.onceWrapper (events.js:300:26)
at ClientRequest.emit (events.js:210:5)
at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
at TLSSocket.socketOnData (_http_client.js:456:22)
at TLSSocket.emit (events.js:210:5)
at addChunk (_stream_readable.js:308:12)
at readableAddChunk (_stream_readable.js:289:11)
at TLSSocket.Readable.push (_stream_readable.js:223:10)
at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:23)
2021-08-19 12:02:48.611 - error: telegram.0 (2956) Exception-Code: ERR_INVALID_ARG_TYPE: The "listener" argument must be of type Function. Received type boolean
2021-08-19 12:02:48.624 - error: telegram.0 (2956) uncaught exception: The "listener" argument must be of type Function. Received type boolean
2021-08-19 12:02:48.625 - error: telegram.0 (2956) TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type boolean
at checkListener (events.js:64:11)
at _addListener (events.js:226:3)
at IncomingMessage.addListener (events.js:284:10)
at IncomingMessage.Readable.on (_stream_readable.js:867:35)
at ClientRequest. (/opt/iobroker/node_modules/iobroker.telegram/main.js:1042:21)
at Object.onceWrapper (events.js:300:26)
at ClientRequest.emit (events.js:210:5)
at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
at TLSSocket.socketOnData (_http_client.js:456:22)
at TLSSocket.emit (events.js:210:5)
at addChunk (_stream_readable.js:308:12)
at readableAddChunk (_stream_readable.js:289:11)
at TLSSocket.Readable.push (_stream_readable.js:223:10)
at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:23)
2021-08-19 12:02:48.626 - error: telegram.0 (2956) Exception-Code: ERR_INVALID_ARG_TYPE: The "listener" argument must be of type Function. Received type boolean
2021-08-19 12:02:48.630 - error: telegram.0 (2956) uncaught exception: The "listener" argument must be of type Function. Received type boolean
2021-08-19 12:02:48.631 - error: telegram.0 (2956) TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type boolean
at checkListener (events.js:64:11)
at _addListener (events.js:226:3)
at IncomingMessage.addListener (events.js:284:10)
at IncomingMessage.Readable.on (_stream_readable.js:867:35)
at ClientRequest. (/opt/iobroker/node_modules/iobroker.telegram/main.js:1042:21)
at Object.onceWrapper (events.js:300:26)
at ClientRequest.emit (events.js:210:5)
at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
at TLSSocket.socketOnData (_http_client.js:456:22)
at TLSSocket.emit (events.js:210:5)
at addChunk (_stream_readable.js:308:12)
at readableAddChunk (_stream_readable.js:289:11)
at TLSSocket.Readable.push (_stream_readable.js:223:10)
at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:23)
2021-08-19 12:02:48.632 - error: telegram.0 (2956) Exception-Code: ERR_INVALID_ARG_TYPE: The "listener" argument must be of type Function. Received type boolean
2021-08-19 12:02:48.635 - error: telegram.0 (2956) uncaught exception: Parse Error: User callback error
2021-08-19 12:02:48.637 - error: telegram.0 (2956) Error: Parse Error: User callback error
at TLSSocket.socketOnData (_http_client.js:456:22)
at TLSSocket.emit (events.js:210:5)
at addChunk (_stream_readable.js:308:12)
at readableAddChunk (_stream_readable.js:289:11)
at TLSSocket.Readable.push (_stream_readable.js:223:10)
at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:23)
2021-08-19 12:02:48.637 - error: telegram.0 (2956) Exception-Code: HPE_CB_HEADERS_COMPLETE: Parse Error: User callback error
2021-08-19 12:02:48.669 - error: telegram.0 (2956) uncaught exception: The "options" argument must be one of type string or Object. Received type boolean
2021-08-19 12:02:48.670 - error: telegram.0 (2956) TypeError [ERR_INVALID_ARG_TYPE]: The "options" argument must be one of type string or Object. Received type boolean
at getOptions (internal/fs/utils.js:207:11)
at Object.writeFile (fs.js:1235:13)
at IncomingMessage. (/opt/iobroker/node_modules/iobroker.telegram/main.js:1032:24)
at IncomingMessage.emit (events.js:215:7)
at endReadableNT (_stream_readable.js:1183:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-08-19 12:02:48.671 - error: telegram.0 (2956) Exception-Code: ERR_INVALID_ARG_TYPE: The "options" argument must be one of type string or Object. Received type boolean
2021-08-19 12:02:48.674 - error: telegram.0 (2956) uncaught exception: The "options" argument must be one of type string or Object. Received type boolean
2021-08-19 12:02:48.675 - error: telegram.0 (2956) TypeError [ERR_INVALID_ARG_TYPE]: The "options" argument must be one of type string or Object. Received type boolean
at getOptions (internal/fs/utils.js:207:11)
at Object.writeFile (fs.js:1235:13)
at IncomingMessage. (/opt/iobroker/node_modules/iobroker.telegram/main.js:1032:24)
at IncomingMessage.emit (events.js:215:7)
at endReadableNT (_stream_readable.js:1183:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-08-19 12:02:48.676 - error: telegram.0 (2956) Exception-Code: ERR_INVALID_ARG_TYPE: The "options" argument must be one of type string or Object. Received type boolean
2021-08-19 12:02:48.679 - error: telegram.0 (2956) uncaught exception: The "options" argument must be one of type string or Object. Received type boolean
2021-08-19 12:02:48.680 - error: telegram.0 (2956) TypeError [ERR_INVALID_ARG_TYPE]: The "options" argument must be one of type string or Object. Received type boolean
at getOptions (internal/fs/utils.js:207:11)
at Object.writeFile (fs.js:1235:13)
at IncomingMessage. (/opt/iobroker/node_modules/iobroker.telegram/main.js:1032:24)
at IncomingMessage.emit (events.js:215:7)
at endReadableNT (_stream_readable.js:1183:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-08-19 12:02:48.681 - error: telegram.0 (2956) Exception-Code: ERR_INVALID_ARG_TYPE: The "options" argument must be one of type string or Object. Received type boolean
2021-08-19 12:02:48.736 - error: telegram.0 (2956) uncaught exception: The "listener" argument must be of type Function. Received type boolean
2021-08-19 12:02:48.737 - error: telegram.0 (2956) TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type boolean
at checkListener (events.js:64:11)
at _addListener (events.js:226:3)
at IncomingMessage.addListener (events.js:284:10)
at IncomingMessage.Readable.on (_stream_readable.js:867:35)
at ClientRequest. (/opt/iobroker/node_modules/iobroker.telegram/main.js:1042:21)
at Object.onceWrapper (events.js:300:26)
at ClientRequest.emit (events.js:210:5)
at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
at TLSSocket.socketOnData (_http_client.js:456:22)
at TLSSocket.emit (events.js:210:5)
at addChunk (_stream_readable.js:308:12)
at readableAddChunk (_stream_readable.js:289:11)
at TLSSocket.Readable.push (_stream_readable.js:223:10)
at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:23)
2021-08-19 12:02:48.738 - error: telegram.0 (2956) Exception-Code: ERR_INVALID_ARG_TYPE: The "listener" argument must be of type Function. Received type boolean
2021-08-19 12:02:48.746 - error: telegram.0 (2956) uncaught exception: Parse Error: User callback error
2021-08-19 12:02:48.747 - error: telegram.0 (2956) Error: Parse Error: User callback error
at TLSSocket.socketOnData (_http_client.js:456:22)
at TLSSocket.emit (events.js:210:5)
at addChunk (_stream_readable.js:308:12)
at readableAddChunk (_stream_readable.js:289:11)
at TLSSocket.Readable.push (_stream_readable.js:223:10)
at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:23)
2021-08-19 12:02:48.748 - error: telegram.0 (2956) Exception-Code: HPE_CB_HEADERS_COMPLETE: Parse Error: User callback error
2021-08-19 12:02:48.756 - error: telegram.0 (2956) uncaught exception: The "options" argument must be one of type string or Object. Received type boolean
2021-08-19 12:02:48.757 - error: telegram.0 (2956) TypeError [ERR_INVALID_ARG_TYPE]: The "options" argument must be one of type string or Object. Received type boolean
at getOptions (internal/fs/utils.js:207:11)
at Object.writeFile (fs.js:1235:13)
at IncomingMessage. (/opt/iobroker/node_modules/iobroker.telegram/main.js:1032:24)
at IncomingMessage.emit (events.js:215:7)
at endReadableNT (_stream_readable.js:1183:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-08-19 12:02:48.758 - error: telegram.0 (2956) Exception-Code: ERR_INVALID_ARG_TYPE: The "options" argument must be one of type string or Object. Received type boolean
2021-08-19 12:02:49.158 - info: telegram.0 (2956) terminating
2021-08-19 12:02:49.161 - warn: telegram.0 (2956) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-08-19 12:02:49.851 - error: host.iobroker2 instance system.adapter.telegram.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-08-19 12:02:49.853 - info: host.iobroker2 Restart adapter system.adapter.telegram.0 because enabled

2021-08-19 12:03:19.905 - info: host.iobroker2 instance system.adapter.telegram.0 started with pid 8529`

**Comment by winnyschuster** [comment]
> when uploading jpg-file to bot i get this errorlog entry

@HFarryranz works here, how are you doing uploads?

**Comment by HFarryranz** [comment]
Using Android with telegramm app. Connected to bot and using the attach Icon.

**Comment by GermanBluefox** [comment]
Fixed in 1.11.0
