### ISSUE TITLE
Fehlermeldung im Browser beim Verlassen der Adapterkonfiguration

### ISSUE THREAD

**Issue by Steff42** [iobroker-community-adapters/ioBroker.telegram#359]
Hallo,
habe die Version 1.14.1 am laufen unter Admin 6.2.0. Beim Verlassen der Telegram-Adapter-Konfiguration schmiert der Browser (Google Chrome Version 103.0.5060.114 Windows) mit "Error in GUI" ab. Durch Reload kann im Anschluss normal weitergearbeitet werden. In der Dev-Console wird der folgende Fehler ausgegeben:

```
instrument.ts:124 ConfigCustomTelegramSet Components TelegramComponent
instrument.ts:124 TypeError: rt is not a function or its return value is not iterable
    at A (4191.a518a3ff.chunk.js:1:394)
    at Ot (conversions.js:67:10)
    at wt (datetime.js:56:19)
    at get weekday [as weekday] (datetime.js:1101:27)
    at v.getDay (date.js:99:28)
    at u._findSchedule (expression.js:566:52)
    at u.next (expression.js:669:23)
    at Jt (InstanceRow.jsx:881:67)
    at Fi (react-dom.production.min.js:167:137)
    at oa (react-dom.production.min.js:290:337)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at ea (react-dom.production.min.js:273:300)
    at hn (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonym) @ instrument.ts:124
Hi @ react-dom.production.min.js:189
i.componentDidCatch.t.callback @ react-dom.production.min.js:190
Yo @ react-dom.production.min.js:144
Zs @ react-dom.production.min.js:261
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
ea @ react-dom.production.min.js:273
hn @ react-dom.production.min.js:127
(anonym) @ react-dom.production.min.js:267
hashchange (async)
value @ Router.js:91
(anonym) @ JsonConfig.jsx:291
(anonym) @ 8596.ff72c56e.chunk.js:1
u @ 8596.ff72c56e.chunk.js:1
onSave @ JsonConfig.jsx:245
(anonym) @ JsonConfig.jsx:338
(anonym) @ 8596.ff72c56e.chunk.js:1
u @ 8596.ff72c56e.chunk.js:1
onClose @ JsonConfig.jsx:338
onClick @ SaveCloseButtons.js:89
ga @ react-dom.production.min.js:54
ka @ react-dom.production.min.js:54
Sa @ react-dom.production.min.js:55
Po @ react-dom.production.min.js:105
To @ react-dom.production.min.js:106
(anonym) @ react-dom.production.min.js:117
ou @ react-dom.production.min.js:274
Ou @ react-dom.production.min.js:52
oi @ react-dom.production.min.js:109
Ql @ react-dom.production.min.js:74
ja @ react-dom.production.min.js:73
O1 @ helpers.ts:99
instrument.ts:124 TypeError: rt is not a function or its return value is not iterable
    at A (4191.a518a3ff.chunk.js:1:394)
    at Ot (conversions.js:67:10)
    at wt (datetime.js:56:19)
    at get weekday [as weekday] (datetime.js:1101:27)
    at v.getDay (date.js:99:28)
    at u._findSchedule (expression.js:566:52)
    at u.next (expression.js:669:23)
    at Jt (InstanceRow.jsx:881:67)
    at Fi (react-dom.production.min.js:167:137)
    at oa (react-dom.production.min.js:290:337)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at ea (react-dom.production.min.js:273:300)
    at hn (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonym) @ instrument.ts:124
Hi @ react-dom.production.min.js:189
i.componentDidCatch.t.callback @ react-dom.production.min.js:190
Yo @ react-dom.production.min.js:144
Zs @ react-dom.production.min.js:261
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
ea @ react-dom.production.min.js:273
hn @ react-dom.production.min.js:127
(anonym) @ react-dom.production.min.js:267
hashchange (async)
value @ Router.js:91
(anonym) @ JsonConfig.jsx:291
(anonym) @ 8596.ff72c56e.chunk.js:1
u @ 8596.ff72c56e.chunk.js:1
onSave @ JsonConfig.jsx:245
(anonym) @ JsonConfig.jsx:338
(anonym) @ 8596.ff72c56e.chunk.js:1
u @ 8596.ff72c56e.chunk.js:1
onClose @ JsonConfig.jsx:338
onClick @ SaveCloseButtons.js:89
ga @ react-dom.production.min.js:54
ka @ react-dom.production.min.js:54
Sa @ react-dom.production.min.js:55
Po @ react-dom.production.min.js:105
To @ react-dom.production.min.js:106
(anonym) @ react-dom.production.min.js:117
ou @ react-dom.production.min.js:274
Ou @ react-dom.production.min.js:52
oi @ react-dom.production.min.js:109
Ql @ react-dom.production.min.js:74
ja @ react-dom.production.min.js:73
O1 @ helpers.ts:99
instrument.ts:124 TypeError: rt is not a function or its return value is not iterable
    at A (4191.a518a3ff.chunk.js:1:394)
    at Ot (conversions.js:67:10)
    at wt (datetime.js:56:19)
    at get weekday [as weekday] (datetime.js:1101:27)
    at v.getDay (date.js:99:28)
    at u._findSchedule (expression.js:566:52)
    at u.next (expression.js:669:23)
    at Jt (InstanceRow.jsx:881:67)
    at Fi (react-dom.production.min.js:167:137)
    at oa (react-dom.production.min.js:290:337)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at ea (react-dom.production.min.js:273:300)
    at hn (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonym) @ instrument.ts:124
Hi @ react-dom.production.min.js:189
i.componentDidCatch.t.callback @ react-dom.production.min.js:190
Yo @ react-dom.production.min.js:144
Zs @ react-dom.production.min.js:261
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
ea @ react-dom.production.min.js:273
hn @ react-dom.production.min.js:127
(anonym) @ react-dom.production.min.js:267
hashchange (async)
value @ Router.js:91
(anonym) @ JsonConfig.jsx:291
(anonym) @ 8596.ff72c56e.chunk.js:1
u @ 8596.ff72c56e.chunk.js:1
onSave @ JsonConfig.jsx:245
(anonym) @ JsonConfig.jsx:338
(anonym) @ 8596.ff72c56e.chunk.js:1
u @ 8596.ff72c56e.chunk.js:1
onClose @ JsonConfig.jsx:338
onClick @ SaveCloseButtons.js:89
ga @ react-dom.production.min.js:54
ka @ react-dom.production.min.js:54
Sa @ react-dom.production.min.js:55
Po @ react-dom.production.min.js:105
To @ react-dom.production.min.js:106
(anonym) @ react-dom.production.min.js:117
ou @ react-dom.production.min.js:274
Ou @ react-dom.production.min.js:52
oi @ react-dom.production.min.js:109
Ql @ react-dom.production.min.js:74
ja @ react-dom.production.min.js:73
O1 @ helpers.ts:99
instrument.ts:124 TypeError: rt is not a function or its return value is not iterable
    at A (4191.a518a3ff.chunk.js:1:394)
    at Ot (conversions.js:67:10)
    at wt (datetime.js:56:19)
    at get weekday [as weekday] (datetime.js:1101:27)
    at v.getDay (date.js:99:28)
    at u._findSchedule (expression.js:566:52)
    at u.next (expression.js:669:23)
    at Jt (InstanceRow.jsx:881:67)
    at Fi (react-dom.production.min.js:167:137)
    at oa (react-dom.production.min.js:290:337)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at ea (react-dom.production.min.js:273:300)
    at hn (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonym) @ instrument.ts:124
Hi @ react-dom.production.min.js:189
i.componentDidCatch.t.callback @ react-dom.production.min.js:190
Yo @ react-dom.production.min.js:144
Zs @ react-dom.production.min.js:261
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
ea @ react-dom.production.min.js:273
hn @ react-dom.production.min.js:127
(anonym) @ react-dom.production.min.js:267
hashchange (async)
value @ Router.js:91
(anonym) @ JsonConfig.jsx:291
(anonym) @ 8596.ff72c56e.chunk.js:1
u @ 8596.ff72c56e.chunk.js:1
onSave @ JsonConfig.jsx:245
(anonym) @ JsonConfig.jsx:338
(anonym) @ 8596.ff72c56e.chunk.js:1
u @ 8596.ff72c56e.chunk.js:1
onClose @ JsonConfig.jsx:338
onClick @ SaveCloseButtons.js:89
ga @ react-dom.production.min.js:54
ka @ react-dom.production.min.js:54
Sa @ react-dom.production.min.js:55
Po @ react-dom.production.min.js:105
To @ react-dom.production.min.js:106
(anonym) @ react-dom.production.min.js:117
ou @ react-dom.production.min.js:274
Ou @ react-dom.production.min.js:52
oi @ react-dom.production.min.js:109
Ql @ react-dom.production.min.js:74
ja @ react-dom.production.min.js:73
O1 @ helpers.ts:99
instrument.ts:124 TypeError: rt is not a function or its return value is not iterable
    at A (4191.a518a3ff.chunk.js:1:394)
    at Ot (conversions.js:67:10)
    at wt (datetime.js:56:19)
    at get weekday [as weekday] (datetime.js:1101:27)
    at v.getDay (date.js:99:28)
    at u._findSchedule (expression.js:566:52)
    at u.next (expression.js:669:23)
    at Jt (InstanceRow.jsx:881:67)
    at Fi (react-dom.production.min.js:167:137)
    at oa (react-dom.production.min.js:290:337)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at ea (react-dom.production.min.js:273:300)
    at hn (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonym) @ instrument.ts:124
Hi @ react-dom.production.min.js:189
i.componentDidCatch.t.callback @ react-dom.production.min.js:190
Yo @ react-dom.production.min.js:144
Zs @ react-dom.production.min.js:261
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
ea @ react-dom.production.min.js:273
hn @ react-dom.production.min.js:127
(anonym) @ react-dom.production.min.js:267
hashchange (async)
value @ Router.js:91
(anonym) @ JsonConfig.jsx:291
(anonym) @ 8596.ff72c56e.chunk.js:1
u @ 8596.ff72c56e.chunk.js:1
onSave @ JsonConfig.jsx:245
(anonym) @ JsonConfig.jsx:338
(anonym) @ 8596.ff72c56e.chunk.js:1
u @ 8596.ff72c56e.chunk.js:1
onClose @ JsonConfig.jsx:338
onClick @ SaveCloseButtons.js:89
ga @ react-dom.production.min.js:54
ka @ react-dom.production.min.js:54
Sa @ react-dom.production.min.js:55
Po @ react-dom.production.min.js:105
To @ react-dom.production.min.js:106
(anonym) @ react-dom.production.min.js:117
ou @ react-dom.production.min.js:274
Ou @ react-dom.production.min.js:52
oi @ react-dom.production.min.js:109
Ql @ react-dom.production.min.js:74
ja @ react-dom.production.min.js:73
O1 @ helpers.ts:99
instrument.ts:124 TypeError: rt is not a function or its return value is not iterable
    at A (4191.a518a3ff.chunk.js:1:394)
    at Ot (conversions.js:67:10)
    at wt (datetime.js:56:19)
    at get weekday [as weekday] (datetime.js:1101:27)
    at v.getDay (date.js:99:28)
    at u._findSchedule (expression.js:566:52)
    at u.next (expression.js:669:23)
    at Jt (InstanceRow.jsx:881:67)
    at Fi (react-dom.production.min.js:167:137)
    at oa (react-dom.production.min.js:290:337)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at ea (react-dom.production.min.js:273:300)
    at hn (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonym) @ instrument.ts:124
Hi @ react-dom.production.min.js:189
i.componentDidCatch.t.callback @ react-dom.production.min.js:190
Yo @ react-dom.production.min.js:144
Zs @ react-dom.production.min.js:261
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
ea @ react-dom.production.min.js:273
hn @ react-dom.production.min.js:127
(anonym) @ react-dom.production.min.js:267
hashchange (async)
value @ Router.js:91
(anonym) @ JsonConfig.jsx:291
(anonym) @ 8596.ff72c56e.chunk.js:1
u @ 8596.ff72c56e.chunk.js:1
onSave @ JsonConfig.jsx:245
(anonym) @ JsonConfig.jsx:338
(anonym) @ 8596.ff72c56e.chunk.js:1
u @ 8596.ff72c56e.chunk.js:1
onClose @ JsonConfig.jsx:338
onClick @ SaveCloseButtons.js:89
ga @ react-dom.production.min.js:54
ka @ react-dom.production.min.js:54
Sa @ react-dom.production.min.js:55
Po @ react-dom.production.min.js:105
To @ react-dom.production.min.js:106
(anonym) @ react-dom.production.min.js:117
ou @ react-dom.production.min.js:274
Ou @ react-dom.production.min.js:52
oi @ react-dom.production.min.js:109
Ql @ react-dom.production.min.js:74
ja @ react-dom.production.min.js:73
O1 @ helpers.ts:99
instrument.ts:124 TypeError: rt is not a function or its return value is not iterable
    at A (4191.a518a3ff.chunk.js:1:394)
    at Ot (conversions.js:67:10)
    at wt (datetime.js:56:19)
    at get weekday [as weekday] (datetime.js:1101:27)
    at v.getDay (date.js:99:28)
    at u._findSchedule (expression.js:566:52)
    at u.next (expression.js:669:23)
    at Jt (InstanceRow.jsx:881:67)
    at Fi (react-dom.production.min.js:167:137)
    at oa (react-dom.production.min.js:290:337)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at ea (react-dom.production.min.js:273:300)
    at hn (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonym) @ instrument.ts:124
Hi @ react-dom.production.min.js:189
i.componentDidCatch.t.callback @ react-dom.production.min.js:190
Yo @ react-dom.production.min.js:144
Zs @ react-dom.production.min.js:261
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
ea @ react-dom.production.min.js:273
hn @ react-dom.production.min.js:127
(anonym) @ react-dom.production.min.js:267
hashchange (async)
value @ Router.js:91
(anonym) @ JsonConfig.jsx:291
(anonym) @ 8596.ff72c56e.chunk.js:1
u @ 8596.ff72c56e.chunk.js:1
onSave @ JsonConfig.jsx:245
(anonym) @ JsonConfig.jsx:338
(anonym) @ 8596.ff72c56e.chunk.js:1
u @ 8596.ff72c56e.chunk.js:1
onClose @ JsonConfig.jsx:338
onClick @ SaveCloseButtons.js:89
ga @ react-dom.production.min.js:54
ka @ react-dom.production.min.js:54
Sa @ react-dom.production.min.js:55
Po @ react-dom.production.min.js:105
To @ react-dom.production.min.js:106
(anonym) @ react-dom.production.min.js:117
ou @ react-dom.production.min.js:274
Ou @ react-dom.production.min.js:52
oi @ react-dom.production.min.js:109
Ql @ react-dom.production.min.js:74
ja @ react-dom.production.min.js:73
O1 @ helpers.ts:99
instrument.ts:124 TypeError: rt is not a function or its return value is not iterable
    at A (4191.a518a3ff.chunk.js:1:394)
    at Ot (conversions.js:67:10)
    at wt (datetime.js:56:19)
    at get weekday [as weekday] (datetime.js:1101:27)
    at v.getDay (date.js:99:28)
    at u._findSchedule (expression.js:566:52)
    at u.next (expression.js:669:23)
    at Jt (InstanceRow.jsx:881:67)
    at Fi (react-dom.production.min.js:167:137)
    at oa (react-dom.production.min.js:290:337)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at ea (react-dom.production.min.js:273:300)
    at hn (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonym) @ instrument.ts:124
Hi @ react-dom.production.min.js:189
i.componentDidCatch.t.callback @ react-dom.production.min.js:190
Yo @ react-dom.production.min.js:144
Zs @ react-dom.production.min.js:261
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
ea @ react-dom.production.min.js:273
hn @ react-dom.production.min.js:127
(anonym) @ react-dom.production.min.js:267
hashchange (async)
value @ Router.js:91
(anonym) @ JsonConfig.jsx:291
(anonym) @ 8596.ff72c56e.chunk.js:1
u @ 8596.ff72c56e.chunk.js:1
onSave @ JsonConfig.jsx:245
(anonym) @ JsonConfig.jsx:338
(anonym) @ 8596.ff72c56e.chunk.js:1
u @ 8596.ff72c56e.chunk.js:1
onClose @ JsonConfig.jsx:338
onClick @ SaveCloseButtons.js:89
ga @ react-dom.production.min.js:54
ka @ react-dom.production.min.js:54
Sa @ react-dom.production.min.js:55
Po @ react-dom.production.min.js:105
To @ react-dom.production.min.js:106
(anonym) @ react-dom.production.min.js:117
ou @ react-dom.production.min.js:274
Ou @ react-dom.production.min.js:52
oi @ react-dom.production.min.js:109
Ql @ react-dom.production.min.js:74
ja @ react-dom.production.min.js:73
O1 @ helpers.ts:99
instrument.ts:124 TypeError: rt is not a function or its return value is not iterable
    at A (4191.a518a3ff.chunk.js:1:394)
    at Ot (conversions.js:67:10)
    at wt (datetime.js:56:19)
    at get weekday [as weekday] (datetime.js:1101:27)
    at v.getDay (date.js:99:28)
    at u._findSchedule (expression.js:566:52)
    at u.next (expression.js:669:23)
    at Jt (InstanceRow.jsx:881:67)
    at Fi (react-dom.production.min.js:167:137)
    at oa (react-dom.production.min.js:290:337)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at ea (react-dom.production.min.js:273:300)
    at hn (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonym) @ instrument.ts:124
Hi @ react-dom.production.min.js:189
i.componentDidCatch.t.callback @ react-dom.production.min.js:190
Yo @ react-dom.production.min.js:144
Zs @ react-dom.production.min.js:261
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
ea @ react-dom.production.min.js:273
hn @ react-dom.production.min.js:127
(anonym) @ react-dom.production.min.js:267
hashchange (async)
value @ Router.js:91
(anonym) @ JsonConfig.jsx:291
(anonym) @ 8596.ff72c56e.chunk.js:1
u @ 8596.ff72c56e.chunk.js:1
onSave @ JsonConfig.jsx:245
(anonym) @ JsonConfig.jsx:338
(anonym) @ 8596.ff72c56e.chunk.js:1
u @ 8596.ff72c56e.chunk.js:1
onClose @ JsonConfig.jsx:338
onClick @ SaveCloseButtons.js:89
ga @ react-dom.production.min.js:54
ka @ react-dom.production.min.js:54
Sa @ react-dom.production.min.js:55
Po @ react-dom.production.min.js:105
To @ react-dom.production.min.js:106
(anonym) @ react-dom.production.min.js:117
ou @ react-dom.production.min.js:274
Ou @ react-dom.production.min.js:52
oi @ react-dom.production.min.js:109
Ql @ react-dom.production.min.js:74
ja @ react-dom.production.min.js:73
O1 @ helpers.ts:99
```

Der Fehler taucht auch mit Edge auf.

Gruß Steffen

**Comment by Steff42** [comment]
Kann es sein, das der Fehler mit alten Node / JS-Controller Versionen zusammenhängt?
Bei auftreten des Fehler war ich auf meinem alten System mit Node 12.12.10 und JSC 3.3.22 unterwegs. Da ich mittlerweile auf mein neu aufgesetztes System umgestiegen bin (Node 16.16.0 / NPM 8.11.0 / JSC 4.0.23) tritt der Fehler nicht mehr auf.

Gruß Steffen

**Comment by GermanBluefox** [comment]
This is an error from admin and was caused by crontrue. The problem was fixed on 14.07.22 in admin
