### ISSUE TITLE
Frage wird automatsich abgebrochen nach xx Sekunden

### ISSUE THREAD

**Issue by peoples0815** [iobroker-community-adapters/ioBroker.telegram#848]
Beim Senden einer Frage über die unten beschriebene Funktion wird nach ca. 15 bis 20 Sekunden die Frage von selbst mit "Nein" beantwortet, unabhängig von dem Zeitlimit das im Adapter eingestellt ist.

**To Reproduce**  

1. Scripte in IoB öffnen
2. Script einfügen und ausführen
3. gesendete Telegramfrage nicht beantworten
4. nach ca. 15 - 20 Sekunden kommt die Meldung: Die Antwort war Nein

**Expected behavior**  
Warten bis zum Ablauf der eingestellten Zeit oder dem auswählen einer Antwort

**Script**  
`
sendTo('telegram.0', 'ask', {
    text: 'Are you sure?',
    reply_markup: {
        inline_keyboard: [
            // two buttons could be on one line too, but here they are on different
            [{ text: 'Yes!',  callback_data: '1' }], // first line
            [{ text: 'No...', callback_data: '0' }]  // second line
        ]
    }
}, msg => {
    // Auf die Antwort reagieren
        if ( msg.data == 'y' ) {
            sendTo("telegram.0", "send", { text: 'Die Antwort war Ja',chatId: 232821635});
        } else {
            sendTo("telegram.0", "send", { text: 'Die Antwort war Nein',chatId: 232821635});
        }   
});

`

**Versions:**  
 - Adapter version: 3.3.2 / 3.9.0
 - JS-Controller version: 5.0.19
 - Node version: v18.20.2
 - Operating system: Debian

**Comment by mcm1957** [comment]
Please attach a log with level denug

**Comment by peoples0815** [comment]
Wenn man das Beispiel aus der Doku verwendet:
`
sendTo('telegram.0', 'ask', {
    user: user, // optional
    text: 'Are you sure?',
    reply_markup: {
        inline_keyboard: [
            // two buttons could be on one line too, but here they are on different
            [{ text: 'Yes!',  callback_data: '1' }], // first line
            [{ text: 'No...', callback_data: '0' }]  // second line
        ]
    }
}, msg => {
    console.log('user says ' + msg.data);
});
`

kommt auch ein Fehler:
`
host.IoBroker
2024-08-16 07:23:46.314	info	instance system.adapter.telegram.0 in version "3.9.0" started with pid 50831
host.IoBroker
2024-08-16 07:23:44.712	info	Restart adapter system.adapter.telegram.0 because enabled
host.IoBroker
2024-08-16 07:23:44.712	error	instance system.adapter.telegram.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
telegram.0
2024-08-16 07:23:44.082	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
telegram.0
2024-08-16 07:23:44.081	info	terminating
telegram.0
2024-08-16 07:23:43.577	error	Exception-Code: ETELEGRAM: ETELEGRAM: 400 Bad Request: message to edit not found
telegram.0
2024-08-16 07:23:43.577	error	Error: ETELEGRAM: 400 Bad Request: message to edit not found at /opt/iobroker/node_modules/node-telegram-bot-api/src/telegram.js:316:15 at tryCatcher (/opt/iobroker/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/opt/iobroker/node_modules/bluebird/js/release/promise.js:547:31) at Promise._settlePromise (/opt/iobroker/node_modules/bluebird/js/release/promise.js:604:18) at Promise._settlePromise0 (/opt/iobroker/node_modules/bluebird/js/release/promise.js:649:10) at Promise._settlePromises (/opt/iobroker/node_modules/bluebird/js/release/promise.js:729:18) at _drainQueueStep (/opt/iobroker/node_modules/bluebird/js/release/async.js:93:12) at _drainQueue (/opt/iobroker/node_modules/bluebird/js/release/async.js:86:9) at Async._drainQueues (/opt/iobroker/node_modules/bluebird/js/release/async.js:102:5) at Async.drainQueues [as _onImmediate] (/opt/iobroker/node_modules/bluebird/js/release/async.js:15:14) at process.processImmediate (node:internal/timers:483:21)
telegram.0
2024-08-16 07:23:43.577	error	unhandled promise rejection: ETELEGRAM: 400 Bad Request: message to edit not found
telegram.0
2024-08-16 07:23:43.576	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
admin.0
2024-08-16 07:23:32.504	info	<== Disconnect system.user.admin from ::ffff:192.168.10.2 javascript
admin.0
2024-08-16 07:23:32.504	info	<== Disconnect system.user.admin from ::ffff:192.168.10.2 javascript
admin.0
2024-08-16 07:23:30.991	info	==> Connected system.user.admin from ::ffff:192.168.10.2
admin.0
2024-08-16 07:23:22.695	info	==> Connected system.user.admin from ::ffff:192.168.10.2
javascript.0
2024-08-16 07:22:58.180	info	script.js.test: user says undefined
javascript.0
2024-08-16 07:22:38.180	info	script.js.test: registered 2 subscriptions, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
javascript.0
2024-08-16 07:22:38.165	info	Start JavaScript script.js.test (Javascript/js)
javascript.0
2024-08-16 07:22:21.707	info	Stopping script script.js.test
`

**Comment by Dome2075** [comment]
Hi,
same issue.

response always trigger after 20 seconds.

**Comment by GermanBluefox** [comment]
Bitte timeout benutzen: Der sendTo-Callback-Timeout des aufrufenden Adapters (JavaScript-Adapter, Default ~20 s) läuft ab, bevor der Telegram-Adapter antwortet. Der JS-Adapter ruft dann den  Callback selbst mit einem Timeout-Ergebnis auf → msg.data ist undefined → der else-Zweig im Script schreibt „Die Antwort war Nein".
